[package]
name = "git-author-rewrite"
version = "0.2.0"
edition = "2024"

[dependencies]
console = "0.16.0"
dialoguer = "0.11.0"
which = "8.0.0"

[dev-dependencies]
libc = "0.2.175"
tempfile = "3.20.0"
